### ISSUE TITLE
Set the @outputclass attribute to "landscape" #1

### ISSUE THREAD

**Issue by abhinavaditya1989** [oxygenxml/dita-classic-pdf-landscape-sample#1]
I want to transform a topic into landscape mode form portrait, I saw that DITA 3.3 onwards this is supported. What should I update in the XSL-fo in order to get the desired result? I guess we need to set the @outputclass attribute to "landscape" on the topicref.
[commons.xsl.txt](https://github.com/abhinavaditya1989/XSLT-FO/files/5026331/commons.xsl.txt)
[topic.xsl.txt](https://github.com/abhinavaditya1989/XSLT-FO/files/5026332/topic.xsl.txt)

**Comment by raducoravu** [comment]
Why did you get the impression that DITA OT 3.3 has native support for landscape orientation of referenced topics?
This DITA Open Toolkit sample plugin I created which can be installed in the publishing engine to change the orientation on topicrefs, but it changes the orientation also for descendant topicrefs inside that topicref.
Maybe you can look at my plugin's contents and use something similar in your plugin.

Also other ways to obtain PDF from DITA, like the Oxygen CSS-based PDF publishing allow rotation of various elements in different ways:
https://www.oxygenxml.com/doc/versions/22.1/ug-editor/topics/dcpp_tables.html
